name: intro_plasma
channels:
  - conda-forge
  - bioconda
  
dependencies:
  - jupyterlab>=3
  - nbresuse
  - python>=3.7
  - pip
  - nodejs
  - r-irkernel
  - r-base>=4
  - r-tidyverse
  - r-ggplot2
  - pip:
    - bash_kernel
